### ISSUE TITLE
Questions about Savoury

### ISSUE THREAD

**Issue by wizonesolutions** [3stack-software/meteor-savoury#1]
What is the `savouryContext` for?

Is it possible to communicate with the progress bar from the server side? How does Savoury know how long the method call is actually taking?

**Comment by nathan-muir** [comment]
So, savoury can be in 4 states: `inactive`(null), `sending`, `complete` and `error`.

`{{> savoury savouryContext}}` just prints the right template & message, based on that state. (`savouryContext` being a reactive data source).

If you want to see how the state is changed, take a look at [`wrapMethod`](https://github.com/3stack-software/meteor-savoury/blob/master/savoury.coffee#L83).

As for progress, you could provide your own `sending` template, and have your method update a collection called `progress`.

eg.

```js
var progress = new Mongo.Collection('someProgress');
Meteor.subscribe('progress');

Meteor.methods({
  myMethod: function(/* args */){
    /* do stuff */
    if (Meteor.isServer){ // ensure that updates aren't simulate on the client
      progress.update({userId: this.userId}, {$inc: {done: 10}, $set: {total: 100}})
    }
  }
});
if (Meteor.isServer){
  Meteor.publish('progress', function(){ return progress.find({userId: this.userId}); });
}
Template.mySendingTemplate.helpers({
  progress: function(){ return progress.findOne({userId: Meteor.userId()}); }
});

/** somewhere else **/

Template.myTemplate.onCreated(function(){
  this.savoury = new Savoury({
   tpl_sending: 'mySendingTemplate'
  });
});
```

```handlebars
<template name="mySendingTemplate">
  {{#with progress}}
    current progress = {{done}} of {{total}}
  {{/with}}
</template>
```

**Comment by wizonesolutions** [comment]
Thanks! Yeah, I figured that using a progress collection might be the way
to go, and no packages seem to provide a pattern for that out of the box
yet.
